### ISSUE TITLE
IOS: app just launches apple maps, no option to choose app for navigation.

### ISSUE THREAD

**Issue by edward962** [dpa99c/phonegap-launch-navigator#100]
On android plugin works fine, but same code doesnt work for ios. On ios it just launches navigation in apple maps.

**Comment by dpa99c** [comment]
As [stated in the documentation](https://github.com/dpa99c/phonegap-launch-navigator#app-detection-selection-and-launching):

> The plugin will detect which supported navigation apps are available on the device.
> By default, where this is more than one choice, it will display a list of these to the user to select for navigation.

Therefore, if only the only supported app installed on the device is Apple Maps (such as in the iOS Simulator), no option to choose the app will be displayed since there's no choice to make.

If more than one supported app is installed on iOS, the native picker will be displayed as illustrated here:

<p align="center">
<img src="http://i.imgur.com/mUg9WqO.gif" />
</p>

You can find which apps are available on the current device using [availableApps()](https://github.com/dpa99c/phonegap-launch-navigator#availableapps)

**Comment by dpa99c** [comment]
Reopen if still an issue
