### ISSUE TITLE
Build fails in ionic on macos 10.12

### ISSUE THREAD

**Issue by petkoe** [dpa99c/phonegap-launch-navigator#101]
Hi,

having the plugin installed (not even used) the build via ionic rc1 fails with 

The following build commands failed:

	Ld build/emulator/xxx.app/xxx normal x86_64
	GenerateDSYMFile build/emulator/xxx.app.dSYM build/emulator/xxxx.app/xxxx
(2 failures)

Can somebody help

thanks 

Peter

**Comment by dpa99c** [comment]
Please clone the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) and build the [IonicExample](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/IonicExample) or [IonicExample2](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/IonicExample2) project to see if you can reproduce this error in an isolated project.

If so, please post details of your build environment (Xcode version, target device) and preferably a zipped XCode project in which the issue is present.

**Comment by petkoe** [comment]
Hello Dave, 

ok, I did a quick upgrade of the v2 ionic demo to rc1 and everything works fine with my config. 

I am in macOS 10.12.1 (latest beta) and use Xcode 8.1. beta

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X Sierra
Node Version: v6.8.1
Xcode version: Xcode 8.1 Build version 8T47 

With the attached "launchnavrc1" everything works. 

When I remove LaunchNavigator from my project it also works.

I have installed as extra plugins:
cordova-plugin-contacts
cordova-plugin-x-socialsharing 
cordova-plugin-compat

After adding them to the attached project I can compile and emulate it.

If I remove LaunchNavigator from my project it compiles and emulates ok. 

[launchnavrc1.zip](https://github.com/dpa99c/phonegap-launch-navigator/files/539275/launchnavrc1.zip)

Peter

**Comment by petkoe** [comment]
Hello Dave,

I did some more removing of plugins and platforms and reinstalling them. I also cleared the ".tmp" directory and now I can compile and emulate it on a simulator for iOS 9.1. I also installed it on iPhone with 9.1 beta. I had to do some more fiddling with temp etc. 
It seems there is a problem with the build process.

Thanks for your support.

Peter
