### ISSUE TITLE
Apple Maps fails when providing a business name as the destination

### ISSUE THREAD

**Issue by MattDHill** [dpa99c/phonegap-launch-navigator#106]
For example: ```launchnavigator.navigate("Chipotle")``` results in "cannot get directions to and from the same location".

Enabling debuging, it appears that the geocoding fails for these types of inputs, getting lat-long of (0,0).

Is there a way to bypass the automatic geocoding and open apps with an exact string parameter? My users are not inputting addresses; most of the time they want to input a location name and find the closest one.

Great plugin btw, thanks!

**Comment by dpa99c** [comment]
The auto-geocoding is there because some supported apps only accept latitude/longitude as inputs. However, I can see there are some instances where disabling this is desirable (see also #93), so on my TODO list is to add an option to disable auto-geocoding. However

**Comment by SquadraCorse** [comment]
Is `not use geocoding` when input is a string still on your roadmap?

**Comment by dpa99c** [comment]
@SquadraCorse Not using geocoding when it's not necessary is on the roadmap - that will be the default. And an option to disable geocoding entirely. 

Because certain apps only support one format of location input (e.g. as lat/lon but not as address), passing an address string as an input location to these apps when geocoding is disabled would result in an error.

It's on my todo list, but I'm pretty busy with work and my own apps right now, so might be a while before I get around to it. Unless a pull request comes along in the meantime.

**Comment by dpa99c** [comment]
This has been fixed in v4 (just published). See #93.
