### ISSUE TITLE
Navigator won't work, even with demo project

### ISSUE THREAD

**Issue by davidvaneekelen** [dpa99c/phonegap-launch-navigator#11]
For a project I'm trying to achieve something for which this plugin should be perfect. However, when I install this plugin using `phonegap plugin add uk.co.workingedge.phonegap.plugin.launchnavigator`, 
adding `<gap:plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" version="2.1.0" />` to the config.xml file, and trying to use the `launchnavigator.navigate(destination, start, successCallback, errorCallback);` command with some plain data, it will always say "Uncaught ReferenceError: launchnavigator is not defined".

I downloaded your demo project and tried that, but whenever I click on one of the navigate button, simply nothing happens.

I've tried both situations on a webbrowser with the Ripple Chrome extention, whilst connecting my iPhone to my PC using the PhoneGap app, and for my own app, distribute it using build.phonegap.com.

**Comment by dpa99c** [comment]
So firstly, the plugin won't work with Ripple because it launches the **native** navigation app - Apple Maps on iOS/Google Maps on Android - hence it will not work on a PC.

`"Uncaught ReferenceError: launchnavigator is not defined"` suggests the plugin has not been loaded since the window.launchnavigator object is created by the plugin.

The iOS demo project needs to be compiled either using the Phonegap CLI or directly in Xcode; it will then run in either the iOS simulator or on a device. Inspect the console output of the device/simulator if you're having issues and post the output here.
