### ISSUE TITLE
Android "Error discovering list of supported apps: Class not found" when calling navigate()

### ISSUE THREAD

**Issue by JeffreyJamesMMM** [dpa99c/phonegap-launch-navigator#110]
Is there a certain cordova version requirement for this plugin? I installed the plugin and when I try to use the navigate function I get "Error discovering list of supported apps: Class not found". I even get this error when my app starts up, without calling any functions.

**Comment by dpa99c** [comment]
The plugin doesn't require any particular version of Cordova. The error message indicates a missing class is being requested somewhere in the [discoverSupportedApps method](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/android/LaunchNavigator.java#L187), so I'm inclined to think it's related to the Android version.
The method is invoked when the plugin (and therefore the host app) is initialized in order to discover which supported apps are available on the device.

I'm unable to reproduce this error, so it would be useful to know the following details:

- Cordova Android platform version
- Android target SDK version
- Build OS (OSX/Windows/Linux)

Even better if you're able to post a zipped Cordova project which illustrates the issue, including the native Android project in `platforms/android`.

**Comment by JeffreyJamesMMM** [comment]
I am unable to provide a zipped Cordova project unfortunately but I can provide versions or other details if you need it.

- Cordova platform ls yields: android 4.0.0
- Target Android SDK: 22 (5.1.1)
- Minimum Android SDK: 16 (4.1.2)
- Project cordova version: 3.5.0-0.2.7
- Cordova CLI version: 5.4.0
- Build OS: Windows 7

I'm going to try running it from Android Studio today to see if I can get a stacktrace or something for you and report back if I find anything.

**Comment by JeffreyJamesMMM** [comment]
Ok it appears that there's some issue with my toolset because something I use didn't update the config.xml in platforms/android/res/xml directory to include the plugin with a feature element.

My project has a plugins/android.json file and I added the feature element to it; now it properly propagates that to config.xml in the platforms directory.

As far as I can tell, it doesn't have anything to do with your plugin but I'll report back if it does end up being something with it.

**Comment by thehungrycoder** [comment]
Just wanted to add (in case someone face similar issue like me), i was getting same error. Seems rebuilding worked; which means I reran the command
```ionic run android .....`
