### ISSUE TITLE
Apple Map is always detected as available in iOS

### ISSUE THREAD

**Issue by svenkeeter** [dpa99c/phonegap-launch-navigator#116]
Even when Apple Maps is uninstalled, running:

```
launchnavigator.availableApps(function(results){
    for(var app in results){
        console.log(launchnavigator.getAppDisplayName(app) + (results[app] ? " is" : " isn't") +" available");
    }
});
```

will always return it as available in iOS

**Comment by dpa99c** [comment]
Before iOS 10, you couldn't delete built-in apps, so the plugin just assumes it's there. 

So it needs updating to check for presence of Apple Maps, just like for any other app.

**Comment by dpa99c** [comment]
https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/CMMapLauncher.m#L143

**Comment by svenkeeter** [comment]
Thank you for your prompt reply. I'll see what i can do about it or just wait for the fix 😃

**Comment by dpa99c** [comment]
It doesn't look like it's possible to detect if Apple Maps is installed or not, since removing it does not actually uninstall the app, it just hides the icon from the home screen.

I'm going by [this SO question](http://stackoverflow.com/questions/39603120/how-to-check-if-apple-maps-is-installed).

So it seems not possible to detect if Apple Maps is unavailable in advance (which is the exact intention of `launchnavigator.availableApps()`.

The best that can be done is to gracefully handle the error when attempting to open Apple Maps using `launchnavigator.navigate()`.

So I think this issue needs to be documented as a caveat rather than fixed as a bug.
