### ISSUE TITLE
launchnavigator is undefined

### ISSUE THREAD

**Issue by Toms88** [dpa99c/phonegap-launch-navigator#134]
Hello,
I have an issue when I try to use your plugin on ios :
When I call the launchnavigator variable it seems to be undefined,
Do I have to compile my app to test it ?
(I am actually using phonegap through the network  to deploy and test my app)
Thanks in advance,
Thomas

**Comment by dpa99c** [comment]
> When I call the launchnavigator variable it seems to be undefined,

This would indicate either the plugin is not installed, is being referenced before it has loaded (before `deviceready` has fired), or is running on an unsupported platform.

> Do I have to compile my app to test it ?
The plugin will only run on the native platform since it requires native code to run and that supported navigation apps be installed on the test device.

See [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) for illustrated examples of how to use the plugin.

**Comment by Toms88** [comment]
It seems that it come from these lines : 
![capture d ecran 2017-06-16 a 14 36 21](https://user-images.githubusercontent.com/8270865/27226915-720280c4-52a1-11e7-8228-3893a909c2ad.png)
![capture d ecran 2017-06-16 a 14 36 21 2](https://user-images.githubusercontent.com/8270865/27226914-72022de0-52a1-11e7-9af9-c7e31404204a.png)

**Comment by dpa99c** [comment]
You appear to be running the Cordova app containing the plugin in a browser emulation of an iOS device, as opposed to on a real iPhone or iPad. This will not work. 
The plugin relies on native code that code can only executed be on the iOS platform.

Hence, in the [plugin definition](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml), "browser" is not a supported platform.

This is the cause of your errors. Please try running your app on a real device.
