### ISSUE TITLE
show icons in app.

### ISSUE THREAD

**Issue by kashikhan1** [dpa99c/phonegap-launch-navigator#149]
in list show icons instead of app name.for example google maps is replace with its icon.

**Comment by dpa99c** [comment]
This is not likely to be implemented soon since it would require significant changes to [cordova-plugin-actionsheet](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet) which is used to display the list of available apps in the default UI provided by the plugin.

If you require this feature, I would suggest creating your own in-app UI which displays icons: you can populate the list of available apps using plugin API functions such as [availableApps()](https://github.com/dpa99c/phonegap-launch-navigator#availableapps)

**Comment by dpa99c** [comment]
Realistically, this is never going to be added to the default UI, which is provided as a simple out-of-the-box solution.
