### ISSUE TITLE
Allowing disallowed apps

### ISSUE THREAD

**Issue by joelbanzatto** [dpa99c/phonegap-launch-navigator#154]
Hello,

I am using launch-navigator and it is really nice, but I want to IGNORE Uber. But it is displayed everytime.

See my code snippet

    function openNativeMap( __latlgn)
    {

        var googleMaps  = launchnavigator.APP.GOOGLE_MAPS;
        var appleMaps   = launchnavigator.APP.APPLE_MAPS;
        var hereMaps    = launchnavigator.APP.HERE_MAPS;
        var wazeMaps    = launchnavigator.APP.WAZE;
        launchnavigator.navigate( __latlgn, {
            appSelection: {
                dialogHeaderText: 'Escolha o app para navegar',
                cancelButtonText: 'Cancelar',
                list: [
                    googleMaps, appleMaps, hereMaps, wazeMaps
                ]
            }
        });

    }

Thanks, guys!

**Comment by dpa99c** [comment]
Make sure you are using v4 of the plugin since the API has changed since v3.

Also see the AdvancedExample in the [example repo](https://github.com/dpa99c/phonegap-launch-navigator-example) which demonstates all of the plugin API features, including [restriction of selectable apps](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L134). You can try building+running it to validate that this works.

**Comment by joelbanzatto** [comment]
Thanks for the quick reply!

Well, I am going to try the v4.

Thanks one more time.
