### ISSUE TITLE
Crashes app when used

### ISSUE THREAD

**Issue by sean-hill** [dpa99c/phonegap-launch-navigator#156]
Hey there,

In my emulator this plugin works like a boss, however on my device it crashes with this error:

    <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIAlertController can only have one action with a style of UIAlertActionStyleCancel'

Any ideas?

**Comment by dpa99c** [comment]
> UIAlertController can only have one action with a style of UIAlertActionStyleCancel

That error is occurring due to [cordova-plugin-actionsheet](https://github.com/EddyVerbruggen/cordova-plugin-actionsheet), on which this plugin [has a dependency](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L55) in order to display the list of apps to the user.
A possible cause is a conflict with another plugin in your project which also defines an action with the `UIAlertActionStyleCancel` style.

A possible solution is to uninstall/re-install this plugin - see #139. 
Or you could implement a custom UI to choose the navigator app (as demonstrated in the Advanced Example[https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/AdvancedExample]), therefore eliminating the need to invoke `cordova-plugin-actionsheet`.

You can confirm this plugin works OK in isolation by building+running the [example projects](https://github.com/dpa99c/phonegap-launch-navigator-example).

**Comment by dpa99c** [comment]
Closed due to no response from OP
