### ISSUE TITLE
IOS Uncaught "options.start.join" is not a function

### ISSUE THREAD

**Issue by raymondtri** [dpa99c/phonegap-launch-navigator#172]
This error only happens with IOS which is strange, here is the code I am calling to activate launchnavigator:
`launchNativeMaps(lat, lng){`
`	let options: LaunchNavigatorOptions = {};`
`	this.launchNavigator.navigate([lat, lng], options);`
`}`

I then receive the error:
`Error: Uncaught (in promise): TypeError: options.start.join is not a function. (In 'options.start.join(",")', 'options.start.join' is undefined) navigate@file:///var/containers/Bundle/Application/7B16B597-B5AF-4F57-B7CB-FDB6E75B7CD4/Socialite.app/www/plugins/uk.c...`

Any thoughts?

**Comment by dpa99c** [comment]
That error looks to be raised by [this line of code](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/ios/launchnavigator.js#L157).

The start parameter is expected to be either an address string, a lat/lon string in the format `"lat,lon"` or an array in the format `[lat,lon]`.

The only way I can see that error being raised is if an object (rather than an array) was passed as the start argument, since the above condition `if(typeof(options.start) === "object")` would evaluate to true but `join()` is not a member function of type `object`, only of type `array`.

For example, this would cause that error:

    launchnavigator.navigate(destination, {
        start: {}
    });
    
There should probably be some better type checking on the inputs to throw a more meaningful error if the wrong type is passed in as an argument.

**Comment by raymondtri** [comment]
I'll get you a more detailed explanation here a bit later today, thanks for the quick reply!

**Comment by raymondtri** [comment]
I am not passing a start parameter, just the LaunchNavigatorOptions = {};
1. Is a start argument required?
2. What is the default type of the start parameter in LaunchNavigatorOptions?

**Comment by dpa99c** [comment]
@raymondtri 

> Is a start argument required?

No.

> What is the default type of the start parameter in LaunchNavigatorOptions? I am just passing an empty array.

[`LaunchNavigatorOptions`](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts#L105) is part of the [Ionic Native Typescript wrapper](https://ionicframework.com/docs/native/launch-navigator/) around this plugin and as such is not under direct control of this plugin. From the looks of [their code](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts#L139) the default type is `string | number[]`.
However, it may be that the compiled JS is wrongly passing an empty object rather than array when start is not defined. The easiest way to check would be to connect Safari Web Inspector to the webview and debug it by placing some breakpoints.

**Comment by indraraj26** [comment]
Hi @raymondtri , 

i am getting same error , how did you managed to resolve ?
https://github.com/ionic-team/ionic-native/issues/2975

Thank you
