### ISSUE TITLE
Launching Android Google Maps with transit transport mode

### ISSUE THREAD

**Issue by swryu0906** [dpa99c/phonegap-launch-navigator#177]
I have a problem with launching turn by turn mode Android Google Maps with "transit" transport mode. There is no problem in launching turn by turn mode Android Google Maps with the other transport modes. Even though "transit" transport mode option is provided, Android Google Maps is launched in driving mode. The following are my test settings and sample code

testing devices: 
. Samsung Galaxy Note 5, Android 7.0
. Samsung Galaxy Tab S2, Android 7.0

Cordova version 8.0.0

launchnavigator.navigate([40.707797, -74.011787], {
    start: [40.750035, -73.987815],
    launchModeGoogleMaps: launchnavigator.LAUNCH_MODE.TURN_BY_TURN,
    transportMode: launchnavigator.TRANSPORT_MODE.TRANSIT
});

Thanks for your attention.

**Comment by dpa99c** [comment]
There is no turn-by-turn navigation for transit mode in Google Maps. This makes sense because you don't need to see every turn that your bus driver or train is making.

**Comment by celron** [comment]
Please reconsider as this is not exactly accurate, google maps does provide step by step directions in transit.

https://arstechnica.com/gadgets/2017/12/google-maps-finally-gets-step-by-step-transit-navigation/

However, I'm not sure that they have enabled it in the api yet.

As an example in  New York to get to a transit stop or connection you may have to walk several minutes to catch a connecting bus, train or boat.  For people who are disabled or don't even understand the language, having the feedback that they have arrived and which way to go  is beneficial.

**Comment by dpa99c** [comment]
@celron The plugin parameters as illustrated above by @swryu0906 will result in the correct URL scheme parameters being generated as [documented for Google Maps for Android](https://developers.google.com/maps/documentation/urls/android-intents#launch_turn-by-turn_navigation).
However, as you can see from that documentation, transport (`mode=t`) is not currently documented as a supported transportation mode when launching turn-by-turn navigation.

Since this was added so recently to the Google Maps Android app, it's likely that the URL scheme has not been updated to support it, hence why @swryu0906 was unable to launch turn-by-turn in transport mode and therefore opened this issue.

If and when the URL scheme for Google Maps for Android is updated to support transport mode for turn-by-turn navigation, this plugin will (as it currently stands) generate the correct URL scheme parameter (`mode=t`) using the options as given in the above example by @swryu0906.
