### ISSUE TITLE
Just want the map to open with the destination searched, not as a destination in a pre-established trip in routing mode

### ISSUE THREAD

**Issue by maceghost** [dpa99c/phonegap-launch-navigator#206]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

Hello, there doesn't seem to be any way to use this plugin to simply open up an external map application, but just with the destination already chosen. Instead, it seems to open directly into the "routing" mode of the app. For example: I give the plug-in the destination "A". After the app I'm running it in allows the user to select which map application to open, the map application opens into a screen that shows a "trip" that has been initiated, from "Your Location", to destination "A". 
Instead, I simply want the map application to open up, and have the destination "A" essentially have already been searched.

**Comment by dpa99c** [comment]
Only a few of the the 3rd party navigation apps supported by this plugin support launching in "maps mode" and this is not the primary purpose of this plugin which is to launch apps in order to directly navigate to a destination. 

As such the requested feature is out of the scope of this plugin. 

It would be best to create a new "launch-map" plugin which specifically supports 3rd party map apps and their URL schemes.
