### ISSUE TITLE
Feature Request: Support for Taxify

### ISSUE THREAD

**Issue by JacoRoos** [dpa99c/phonegap-launch-navigator#209]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

# Feature request

### Add support for Taxify
Please consider adding support for the Taxify app: https://taxify.eu/

### Problem to solve
The current implementation of the user choice popup lists Taxify when it is installed on a device. However, the destination does not make it into the Taxify app. Full disclosure, this was tested using the Ionic Native wrapper for this plugin: https://ionicframework.com/docs/native/launch-navigator/

**Comment by dpa99c** [comment]
> Please consider adding support for the Taxify app: https://taxify.eu/

I don't see any link to developer documentation on the Taxify site which references an app URL scheme or deep links. Please provide a link to the documentation if it exists otherwise this issue will be closed - I cannot implement a URL scheme that does not exist.

> The current implementation of the user choice popup lists Taxify when it is installed on a device. However, the destination does not make it into the Taxify app

Presumably you tested this on Android, which would indicate the Taxify app makes use of the generic `geo://` URL scheme on Android, however this is not the same as supporting its own custom URL scheme.

**Comment by dpa99c** [comment]
Closed due to no response
