### ISSUE TITLE
Plugin not usable in Intel XDK anymore

### ISSUE THREAD

**Issue by piet5211** [dpa99c/phonegap-launch-navigator#21]
Somewhere between june 18 2015 and now something happened such that, when building with intel XDK, a 
"plugin failed"
when trying to build an app.

The june 18 version works when building in intel XDK.

**Comment by dpa99c** [comment]
The latest version of the plugin adds a dependency on the [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation). The Cordova 5 CLI satisfies this dependency automatically and installs the geolocation plugin, but it seems that Intel XDK may not. Try manually adding the geolocation plugin to your project. If that works, I'll update the documentation accordingly.

**Comment by piet5211** [comment]
Thanks, that worked! Mind that the standard cordova or intel XDK geolocation plugins do not work, as I have tried before. You have to use https://github.com/apache/cordova-plugin-geolocation, as you indicate.
Thanks again and for your fast answer.

**Comment by dpa99c** [comment]
I've removed the dependency on the geolocation plugin due to issues caused by other plugins having dependencies on different geolocation plugins [see here](https://github.com/dpa99c/phonegap-launch-navigator/issues/22). 
So instead, I've made installing the geolocation plugin a recommendation for the iOS/Windows platforms rather than an automated dependency. The latest version of the plugin (2.8.0) implements this.
