### ISSUE TITLE
launchnavigator not defined in IOS

### ISSUE THREAD

**Issue by gianluigi1961** [dpa99c/phonegap-launch-navigator#224]
Hi,
I have a problem using the launchnavigator in IOS, it work well in Android, but in IOS launchnavigator is not defined

Compiled with Visual studio and remote build on Mac Mojave
I use IOS engine 4.3.0 and in the source folder I can see the uk.co.workingedge.phonegap.plugin.launchnavigator folder but in the resulting folder on my Mac the plugin is not present and running the app the launchnavigator is not defined

May you help me?

Thanks
Gianluigi

![Untitled-3](https://user-images.githubusercontent.com/53263400/61808297-6c9c5900-ae3b-11e9-832a-34198ee05d92.jpg)
![Untitled-2](https://user-images.githubusercontent.com/53263400/61808304-6efeb300-ae3b-11e9-9d89-305f3ea0ca23.jpg)

**Comment by dpa99c** [comment]
It looks like the plugin has not been installed properly but this isn't something I can help you with since the problem is with your development environment not the plugin.
Please use the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to validate that the plugin works properly on iOS.
