### ISSUE TITLE
Can i show launcher app logo to google map navigator app, to come back and push user current position to my server.

### ISSUE THREAD

**Issue by kapil019** [dpa99c/phonegap-launch-navigator#237]
# Feature request

I need my app logo on Google navigator app, 
User can come back to my app on clicking on logo.
I also need to track current position of user.
Like OLA can and Uber open Google navigator with there logo.

**Comment by dpa99c** [comment]
While the Google Maps app on iOS supports a [callback mechanism](https://developers.google.com/maps/documentation/urls/ios-urlscheme#specify_a_callback_url), the documentation makes it clear this does not work in turn-by-turn navigation mode:

> Note: Buttons added via the x-source parameter will not be displayed in the turn-by-turn navigation UI.

Since the purpose of this plugin is to launch 3rd party apps for turn-by-turn navigation, this is therefore out-of-scope for this plugin.

Also [Google Maps on Android](https://developers.google.com/maps/documentation/urls/android-intents) does not support any equivalent callback mechanism.
