### ISSUE TITLE
Not recognizing google_maps on iOS

### ISSUE THREAD

**Issue by skeditAdmin** [dpa99c/phonegap-launch-navigator#239]
Using Ionic 4 with Capacitor

uk.co.workingedge.phonegap.plugin.launchnavigator version 5.0.4

Since upgrading to Capacitor, launch navigator no longer recognizes google maps.

Google maps is installed:
![Google-Maps](https://user-images.githubusercontent.com/55203099/72579021-144b8e80-3895-11ea-8010-22e714ffe944.png)

Running the following code:

```			
constructor(private launchNavigator: LaunchNavigator) {}
...
ngOnInit() {
    const availableApps = await this.launchNavigator.availableApps();
    alert(JSON.stringify(availableApps));
}
```

gives me the following:

![info](https://user-images.githubusercontent.com/55203099/72579491-807ac200-3896-11ea-853c-c8bf1c39c08d.png)

**Comment by dpa99c** [comment]
This is a Cordova plugin - Capacitor is not a supported environment.

**Comment by skeditAdmin** [comment]
Capacitor can use Cordova plug ins.  I'm using several other plug-ins, and everything else about your plug-in works except for the google maps.

The fact that it shows "apple_maps: true" shows me that it's working.  I can open Apple maps just fine.  Just not google maps.

**Comment by sbannigan** [comment]
@skeditAdmin this plugin does work with Capacitor. When you run `npx cap update` [after installing the plugin](https://capacitor.ionicframework.com/docs/basics/workflow#4-update-the-native-project), you should see this warning:
```
[warn] Plugin uk.co.workingedge.phonegap.plugin.launchnavigator requires you to add 
  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>citymapper</string>
    <string>comgooglemaps</string>
    <string>navigon</string>
    <string>transit</string>
    <string>waze</string>
    <string>yandexnavi</string>
    <string>uber</string>
    <string>tomtomhome</string>
    <string>com.sygic.aura</string>
    <string>here-route</string>
    <string>moovit</string>
    <string>lyft</string>
    <string>mapsme</string>
    <string>cabify</string>
    <string>baidumap</string>
    <string>taxis99</string>
    <string>iosamap</string>
  </array>
 to your Info.plist to work
```
Because Cordova normally handles building the Info.plist using each plugin's config, but Capacitor allows you to manage the native platform files yourself, you must add this manually. After you add it you will no longer see the warning message when updating plugins and the `availableApps()` functionality should work correctly.
