### ISSUE TITLE
launchNavigator  ios 14.4  Error. UIAlertController can only have one action with a style of UIAlertActionStyleCancel'

### ISSUE THREAD

**Issue by khaledpro2012** [dpa99c/phonegap-launch-navigator#263]
error on ios
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIAlertController can only have one action with a style of UIAlertActionStyleCancel'
terminating with uncaught exception of type NSException
(lldb) 

code
  let options: LaunchNavigatorOptions = {
              start: currentlocation ,
              appSelection: { rememberChoice: { enabled: false } }
            };
            this.launchNavigator.navigate(this.destination , options)
                .then(
                  success => console.log('Launched navigator' ,success),
                  error => console.log('Error launching navigator', error)
              );

**Comment by dpa99c** [comment]
This is insufficient information. 
Please fill out the bug issue template completely and ensure you have regression tested using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to rule out issues in your project.
If the example project works, please list all other plugins in your own project as this may be caused by a plugin conflict.
