### ISSUE TITLE
[iOS] org.apache.cordova.geolocation required to build?

### ISSUE THREAD

**Issue by BrunoCartier** [dpa99c/phonegap-launch-navigator#27]
Hey,

Your plugin is really useful, many thanks for it.

I face a problem, though:

When I try to build my app on iOS, I get the following error:
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CLLocation", referenced from:
      objc-class-ref in LaunchNavigator.o
  "_OBJC_CLASS_$_CLGeocoder", referenced from:
      objc-class-ref in LaunchNavigator.o
  "_CLLocationCoordinate2DMake", referenced from:
      -[LaunchNavigator setAppleDestination] in LaunchNavigator.o
      -[LaunchNavigator setAppleStart] in LaunchNavigator.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am forced to install `org.apache.cordova.geolocation` to be able to build it.

This is sad, for two reasons:
- It is not documented in the README.md
- I do not need geolocation on my app

What do you think about this?

**Comment by dpa99c** [comment]
This looks to be a bug in my new iOS implementation, not an intentional dependency on the geolocation plugin; that is accidental.

The most recent version of the plugin contains a rewrite of the iOS native code in order to invoke Apple Maps directly rather than via its URL scheme. This allows more options to be passed to Apple Maps such as transport mode. It also means the plugin has more native dependencies; the MapKit framework for one. It seems that MapKit itself depends on the CoreLocation framework, which the geolocation plugin includes, but the launch navigator plugin currently does not include CoreLocation. My test project contains the geolocation plugin, so I didn't notice this missing dependency when testing it.

So I'll release an updated version of the plugin which includes the missing dependency.

Thanks for reporting this bug; in the meantime, I will offer you a full refund ;-)

**Comment by BrunoCartier** [comment]
This fixes the issue. Thanks a lot!

Keep up the good work :)
