### ISSUE TITLE
Android is fine, iOS console giving me error

### ISSUE THREAD

**Issue by azn1viet** [dpa99c/phonegap-launch-navigator#35]
module uk.co.workingedge.phonegap.plugin.launchnavigator.LaunchNavigator already defined

Error: Module uk.co.workingedge.phonegap.plugin.LaunchNavigator.LaunchNavigator does not exist.

Not sure about this error since I tried to remove/add it many times.
Any suggestions?

**Comment by dpa99c** [comment]
- Try removing plugin via CLI: `cordova plugin rm uk.co.workingedge.phonegap.plugin.launchnavigator`
- Then check to see if plugin exists under legacy ID with capitals in plugins dir: `ls plugins`
- See if `uk.co.workingedge.phonegap.plugin.LaunchNavigator` exists
- If so, remove it: `cordova plugin rm uk.co.workingedge.phonegap.plugin.LaunchNavigator`
- Check plugins/fetch.json for zombie entries once plugin is removed
- Remove/re-add iOS platform: `cordova platform rm ios && cordova platform add ios`

**Comment by dpa99c** [comment]
Is this still a problem?

**Comment by azn1viet** [comment]
Will work on this today and post a new status.

Regards,

Dean Le

**Comment by azn1viet** [comment]
it doesn't give me any more errors but takes me to nowhere. It doesn't call the navigator launcher. iOS 9.2. Note that Android is still fine with the same code.

**Comment by azn1viet** [comment]
here is the iOS console:

__NSArrayM boolValue]: unrecognized selector sent to instance 0x14fc584f0
2016-01-04 14:55:18.158 DD Restaurant[1262:1080184] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM boolValue]: unrecognized selector sent to instance 0x14fc584f0'
*** First throw call stack:
(0x182019900 0x181687f80 0x18202061c 0x18201d5b8 0x181f2168c 0x1001846b8 0x10019deac 0x10019d778 0x10019ed34 0x1829dbe20 0x181fd0efc 0x181fd0990 0x181fce690 0x181efd680 0x18340c088 0x186d74d90 0x10006910c 0x181a9e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by dpa99c** [comment]
OK, I will have a look into this tomorrow and get back to you.

**Comment by bhagat2015** [comment]
Hi @dpa99c , I have the same issue. It is working fine in Android but in IOS i am getting the following error
Error : Failed to load webpage with error: The URL can’t be shown

**Comment by dpa99c** [comment]
@azn1viet I've tested the plugin thoroughly on various versions of iOS up to and including v9.2 and I'm unable to reproduce such an error:

> __NSArrayM boolValue]: unrecognized selector sent to instance 0x14fc584f0

It's hard to be sure the cause of the error without seeing a full stack trace to find the offending line number. However, from the looks of the error I would say it's a typing issue, i.e the wrong type being sent from Javascript to the Objective-C part of the plugin. iOS seems more sensitive to this than Android, hence why Android is working fine. The plugin could probably do with a bit tighter input checking to explicitly flag bad input types, but for now my suggestion is to have a look at the [example usage](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/LaunchNavigatorExample/www/index.js) in the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to check if this concurs with your implementation.

If you have no luck there, I suggest using something like `console.dir()` in Javascript to dump out the input variables and post them here so I can have a look. You could also try using the example input values in the example project in your own implementation to eliminate bad typing as cause of the problem.

**Comment by dpa99c** [comment]
@bhagat2015 It's not the same issue, otherwise the error would be the same as that posted by @azn1viet. 

With just that error message and no contextual information, it's hard for me to tell you the root cause of the problem - some for info would help such as does that message appear in the XCode/Objective-C log output or in the Javascript console output?

Off the top of my head, my guess would be that with the whitelist plugin added, the `Content-Security-Policy` meta-tag is blocking the app from accessing the required URL spaces. You could try tweaking it to something like this:

    <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">

Or try removing the whitelist plugin from the project.

Again, look at the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) for guidance as this is tested and working properly on iOS. 

Other possible causes could be interference from other plugins or code, so my suggestion is to create an isolated test case in a separate project (possible using the example project as a starting point) and work out from there.

**Comment by dpa99c** [comment]
@azn1viet Can this be closed?
