### ISSUE TITLE
Permission popups bypassed on plugin launch

### ISSUE THREAD

**Issue by asartz** [dpa99c/phonegap-launch-navigator#45]
Hi there,
i have noticed a strange behavior of the plugin. I am using ionic and the code that launches the plugin is:
$cordovaLaunchNavigator.navigate([$scope.appService.map.options.lat, $scope.appService.map.options.lng], null, {
         preferGoogleMaps: false,
         transportMode: "driving",
         enableDebug: true,
         disableAutoGeolocation: false
       }).then(function () {
         console.log("Navigator launched");
       }, function (err) {
         console.error(err);
       });
As you can see in the video below as soon as the user presses the button to get map directions and the map app is launched the confirmation messages are popping up for 2-3 seconds but the process continues without waiting for the user to confirm or not.
This behavior changes when parameter disableAutoGeolocation is true. What happens in this case is that (if user has location services enabled) the plugin proceeds opening the map app without any confirmation popups.
Is there any way to force the whole process to wait the users approval? 
I am attaching the video [https://www.youtube.com/watch?v=Wt_wap4naCg](url)

Thanks in advance.

**Comment by dpa99c** [comment]
The dialog that's displayed when the app first requests permission to use location is triggered by this plugin when `disableAutoGeolocation == false` by invoking the W3C geolocation API in the WebView to retrieve the current location (via `cordova-plugin-geolocation`). However, the actual display of the dialog is controlled by the iOS location manager and is asynchronous, hence it's not possible to "delay" the plugin from launching the navigation app, since it has no reference as to whether that dialog has been displayed or dismissed.

In contrast, by setting `disableAutoGeolocation == true`, the plugin does not attempt to use the W3C geolocation API (via `cordova-plugin-geolocation`) to retrieve current position and instead uses native iOS functionality to obtain current location and pass it to the navigation app. This does not require the user to explicitly grant permission to use location, hence no dialog is displayed.

If you want to continue using the W3C geolocation API (`disableAutoGeolocation == false`) but want to get the requesting of location permission out the way before launching the navigation app, you can use another of my plugins, [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin), to check/request access to location before calling the launch-navigator plugin. Something like this:

    function launchNavigation(){
        $cordovaLaunchNavigator.navigate([$scope.appService.map.options.lat, $scope.appService.map.options.lng], null, {
        preferGoogleMaps: false,
        transportMode: "driving",
        enableDebug: true,
        disableAutoGeolocation: false
        }).then(function () {
        console.log("Navigator launched");
        }, function (err) {
        console.error(err);
        });
    }

    function requestLocationPermission(){
        // watch for permission request response
        cordova.plugins.diagnostic.registerLocationAuthorizationStatusChangeHandler(function(status){
            console.log("Location authorization status changed from \"not_determined\" to: "+status);
            switch(status){
                case "denied":
                    console.error("User denied location access");
                    break;
                default:
                    // user has granted access
                    launchNavigation();
            }
        });

        // request permission
        cordova.plugins.diagnostic.requestLocationAuthorization(function(){
            console.log("Successfully requested location authorization");
        }, function(error){
            console.error(error);
        });|
    }

    cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
        console.log("Location authorization status: " + status);
        switch(status){
            case "not_determined":
                requestLocationPermission();
                break;
            case "denied":
                console.error("User denied location access");
                break;
            default:
                // user has already granted access
                launchNavigation();
        }
    }, onError);

**Comment by asartz** [comment]
Works like a charm. That is the exact behaviour i wanted to achieve. 
Thank you for your help.
