### ISSUE TITLE
iOS Apple Maps zooms out to globe for several seconds

### ISSUE THREAD

**Issue by trenthm** [dpa99c/phonegap-launch-navigator#50]
First off: thanks for this plugin! I love that it can work without requiring user permissions (disableAutoGeolocation: true).

When I run something like this:
```
launchnavigator.navigate(address, null, function () {
    console.log("successful directions");
}, function (err) {
    console.log("error with directions: " + err);
}, {
    disableAutoGeolocation: true
});
```

Most of the time Apple Maps starts with the map near my location, but then it **zooms out to the entire globe and sits there for several (~5) seconds before zooming back to the proper level.**

I understand that I am not providing it with any information about my whereabouts (null), but I've never seen this behavior before.

It's unlikely to be related, but I noticed that the plugin has a "UK" prefix. Is there anything in the code that might encourage the map to think it should start in the UK (I'm in the US)? For instance, it starts zoomed in near my location (I'm guessing due to caching my recent location), then something the plugin communicated makes it "think" globally, and then it finally figures out my location.

**Comment by dpa99c** [comment]
When you set `disableAutoGeolocation: true`, the plugin tells Apple Maps to use the current device location as the start location. This can take Apple Maps a few seconds, e.g. to acquire a GPS lock/network triangulation. While Apple Maps is waiting for a current location, it zooms out, then zooms back in once it has a locaiton fix. This behaviour is entirely within the Apple Maps app - this plugin has no control over that. The "uk" prefix on the plugin has nothing to do with it. That's simply part of the package name. 
Hence, closing since this is not an issue with the plugin itself, just the behaviour that Apple has put into Apple Maps.

**Comment by trenthm** [comment]
Ok. Thanks for the info, and the swift reply!

(I didn't really think "UK" had anything to do with it, but was just trying to imagine a way for Apple Maps to go "global.")

Thanks again for the plugin!
