### ISSUE TITLE
Android build fail when use Cordova 6.1.0，iOS not try yet 

### ISSUE THREAD

**Issue by bau720123** [dpa99c/phonegap-launch-navigator#54]
hi @dpa99c 

[my environment]
Cordova 6.1.0
Cordova-Android 5.1.1
Java Version，1.8.0_66

see my screenshot
![screenshot](https://cloud.githubusercontent.com/assets/5110085/14037288/d0460768-f27c-11e5-959a-05e237e8d3f8.png)

after some survey，it seem when I use Cordova 6.1.0 and no mater which "phonegap-launch-navigator" version that I use，it will cause build fail

**Comment by dpa99c** [comment]
From you build error this looks to be caused because Gradle is failing to satisfy the dependency on the `org.apache.http.legacy` library.

The Android implementation now automatically geocodes/reverse-geocodes supplied locations to pass them to apps in the required format. To do this it uses the `org.apache.http.legacy` library which should be automatically pulled in by Gradle at build time.

I have a feeling this might be causing an error because it needs an additional component to be installed via the Android SDK Manager which I have installed and you do not.

I will investigate and if this is the case, I'll update the documentation to make it explicitly clear which Android SDK component must be installed.

**Comment by dpa99c** [comment]
Just looking [here](http://stackoverflow.com/questions/33914589/gradle-failed-to-sync-with-unable-to-find-optional-library) and [here](http://stackoverflow.com/questions/33898857/why-warningunable-to-find-optional-library-org-apache-http-legacy-occurs) and it seems that `org.apache.http.legacy` can have lots of different causes.

So I think it maybe best just to replace it with the HttpURLConnection class which is supported on Android 2.3 (API level 9) and above. I'll release this in an update.

**Comment by dpa99c** [comment]
I've just published v3.0.1 to npm. Try building with this. It replaces `org.apache.http.legacy` with OkHttp client for Android. Should fix your build issue.

**Comment by bau720123** [comment]
awesome @dpa99c 
solved

**Comment by bau720123** [comment]
hi @dpa99c 
this is another plugin that will build fail too when I use Cordova 6.1.0
but it's situation seem some different from yours
if could or you have free time，maybe you can give @jeduan some suggestion
very appreiciate
