### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by ihadeed** [dpa99c/phonegap-launch-navigator#55]
Hey there,

Great plugin, thanks for your efforts!

I noticed in your v3 API you have moved the success/error callbacks to be inside the `option` parameter's object. I would like to understand what lead you to switch to this approach instead.

The reason I'm asking is because I'm one of the developers for the [Ionic Native Repo](https://github.com/driftyco/ionic-native). It basically wraps plugins to provide Promise or Observable approach instead of the default success/error callback methods approach. Currently, it does that by working with successCallback/errorCallback parameters which are commonly used by most developers. But now that you are in the process of updating your API we would have to write additional code to be able to support your plugin.

I look forward to hearing back from you.

**Comment by dpa99c** [comment]
The reason I've moved the success and error callbacks inside of the `options` parameter is because they are also optional. The only required parameter is `destination`, so all keys on the `options` object, and the `options` object itself are optional. Therefore in the simplest scenario, the plugin can be invoked with a single parameter:

    launchnavigator.navigate("Some place");

While I could move them back out into the function signature again (e.g. `navigate(destination, successFn, errorFn, options)`), I am reluctant to do some because it makes for an unclean API when calling the plugin. 
For example, if I want to specify some options but not the callbacks, I have to remember to supply `null` for the arguments I'm not using, for example:

    launchnavigator.navigate("Some place", null, null, {some: options});

In the case of this plugin, the success callback is that useful since the outcome results in another app being launched and the current Cordova app which is using this plugin being paused in the background, and therefore the success function is not evaluated until the app using this plugin is returned to the foreground.

I have an item on my todo list to implement a generic angular service which wraps the Cordova API of this plugin, in order to provide a deferred promise interface. This would be bundled with the plugin and instantiate itself if `window.angular` is defined. If I bring this up my priority list and implement it, would that solve your problem?

**Comment by ihadeed** [comment]
Thanks for the quick response!

Ah, I understand now.

Would be a good idea to implement it the following way?

```js
ln.v2.navigate = function(destination, start, successCallback, errorCallback, options) {
    // Supply options only. Skip success/error callbacks.
    if(arguements.length === 3 && typeof arguements[2] != 'function')
        options = successCallback;

    // Supply successCallback and options
    if(arguements.length === 4 && typeof arguements[3] != 'function')
        options = errorCallback;
    

    ...
};
```


If you create a wrapper method that returns a promise that would help too.

**Comment by dpa99c** [comment]
`ln.v2.navigate` is deprecated and will be removed in a future release, so I'd prefer to do any conditional switching in `ln.navigate`; something like:

    ln.navigate = function(){
        if(arguments.length <= 2 && (typeof(arguments[1] == "undefined" || typeof(arguments[1] == "object")))){
            ln.v3.navigate.apply(this, arguments);
        }else if(typeof(arguments[1] == "function") && (typeof(arguments[2] == "undefined" || typeof(arguments[2] == "function")){
            // called with v3 signature: navigate(start, successCallback, errorCallback, options)
            var options = typeof(arguments[3] == "object") ? arguments[3] : {};
            options.successCallback = arguments[1];
            options.errorCallback = arguments[2];
            ln.v3.navigate.apply(this, arguments);
        }else{
            ln.v2.navigate.apply(this, arguments);
        }
    };
    
Does that work for you?

**Comment by ihadeed** [comment]
Yeah, that works! 
It basically provides backwards compatibility which is great.

**Comment by dpa99c** [comment]
Ok, will implement this when I get some time

**Comment by ihadeed** [comment]
Thanks Dave, I appreciate it.

**Comment by ihadeed** [comment]
Hey @dpa99c 

I was just looking at your code to implement the new functions.

First I would like to say great job! The plugin is looking much better than before, the new stuff is really impressive.

I'm replying to this issue because this is kinda related, I was looking at this: https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/common.js#L397
and I noticed that it only supports the callbacks through the `options` parameter. 

I was wondering why are you using the `options` parameter instead of adding optional `successCallback` and `errorCallback` as the last two parameters?

**Comment by inplamba** [comment]
Hey @dpa99c
I am Using Launch Navigator ,Can this plugin provide success callback (Means when we reached the destination in google maps from starting point) it gives us success that user reached the destination 

Thanks in Advance

**Comment by inplamba** [comment]
Hey @dpa99c
Please Respond ,I am Using Launch Navigator ,Can this plugin provide success callback (Means when we reached the destination in google maps from starting point) it gives us success that user reached the destination

Thanks in Advance

**Comment by ihadeed** [comment]
I recommend that you open a new issue with your problem side this is closed
already.
