### ISSUE TITLE
Facing Api issue in iOS 

### ISSUE THREAD

**Issue by Prav92** [dpa99c/phonegap-launch-navigator#70]
When i am trying to click the launch navigator in map page it should throw the warning, **"launchnavigator.navigate() called using deprecated v2 API signature. Please update to use v3 API signature as deprecated API support will be removed in a future version "**

**Comment by dpa99c** [comment]
You are seeing this warning because you are calling the plugin using the deprecated v2 API signature of the `navigate` function:

    launchnavigator.navigate(destination, start, successCallback, errorCallback, options);

As [stated in the documentation](https://github.com/dpa99c/phonegap-launch-navigator#legacy-v2-api), the v2 API is deprecated and will be removed in a future release.

You should update your usage of the plugin to call it using the [v3 API signature](https://github.com/dpa99c/phonegap-launch-navigator#navigate) for the `navigate` function:

    launchnavigator.navigate(destination, options);

So, rework your call to the `navigate` function so only 2 parameters are being passed: `destination` and `options`
