### ISSUE TITLE
Plugin doesn't support this project's cordova version. cordova: 3.9.2, failed version requirement: >=4.0.0

### ISSUE THREAD

**Issue by sunil-jhamnani** [dpa99c/phonegap-launch-navigator#74]
Tried installing the plugin using the Cordova CLI and also adding the github URL to the config.xml file but it says that the plugin is only compatible with the cordova version <=4.0.0.

Please let me know how can i resolve this.

**Comment by dpa99c** [comment]
`cordova-cli@3.9.2` is very old and is not supported by this plugin. At least `cordova-cli@4` is required, because prior to this, Cordova used an Ant-driven build process, while `cordova-cli@4+` uses Gradle, which this plugin relies on to load its Android dependencies. Also, a minimum of `cordova-android@5` is required by this plugin because it requires components from Android API 23 for Android 6.0 run-time permissions functionality.

There's no reason to be running such as old version of the Cordova CLI and it will only cause you problems. 

I suggest updating your Cordova CLI version (`npm install -g cordova@latest`).

I also suggest updating the Android platform: to do so, run the following from your Cordova project folder (i.e. contains `www/`, `platforms/`, `plugins/`, etc.): `cordova platform rm android && cordova platform add android@5`
