### ISSUE TITLE
Cannot find name 'launchnavigator'

### ISSUE THREAD

**Issue by striff** [dpa99c/phonegap-launch-navigator#75]
Hello,

I am using your plugin on Ionic 2 with Angular 2 on Typescript. It works perfectly despite the fact that I get this error from Typings I belive:

> Cannot find name 'launchnavigator'.

How should I define it so that I will get rid of this typescript error.

All the best,
striff

**Comment by dpa99c** [comment]
I have to admit that I haven't tested the plugin with Ionic 2/Angular 2/Typescript environment, but this gives me reason to. Leave it with me...

**Comment by wmru** [comment]
+1

**Comment by dpa99c** [comment]
Yes, as @wmru says, Ionic team have officially added support for this plugin. 

However, this error may occur for other plugins which are not officially supported yet, so here is a workaround in the meantime:

If you get an error like this:

    Error TS2304: Cannot find name 'launchnavigator'.

it is because there's no type definition for the plugin. You can rectify this with a simple Typescript declaration:

    declare var launchnavigator:any;
