### ISSUE TITLE
Option to go back to app after navigation finished?

### ISSUE THREAD

**Issue by mcbejn** [dpa99c/phonegap-launch-navigator#8]
Hi guys,

Is there any solution to get back in the app after the native navigation app has been loaded with the plugin?

Greets!

**Comment by dpa99c** [comment]
On Android, pressing the hardware back button in the native navigation app will return focus to the app that launched it.

However on iOS, the [Apple Maps URL scheme](https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1) appears not to support any mechanism for going back in this way.

Google Maps for iOS does provide a [callback mechanism](https://developers.google.com/maps/documentation/ios/urlscheme#add_a_back_button_to_google_maps_for_ios) to go back, so one option would be to extend the plugin to allow a choice of Apple Maps or Google Maps on iOS. As outlined in the Google documentation, your app would need to register its own URL scheme for this to work.

On Windows Phone 8, it seems back functionality can be achieved with a bit of a [native code workaround](http://stackoverflow.com/questions/21433190/bing-map-back-button-cant-return-to-my-app-wp8)

**Comment by dpa99c** [comment]
The plugin now supports the option to prefer Google Maps to Apple Maps on iOS; this will use Google Maps if it's installed, otherwise fall back to Apple Maps.

It also (currently unofficially) supports the x-callback mechanism; if your iOS app implements its own URL scheme, this can be passed to Google Maps via the plugin, which will cause "Back" button to appear in Google Maps on iOS.

Example usage would be:

    launchnavigator.navigate(
      "London, UK",
      "Manchester, UK",
      function(){
        alert("Plugin success");
      },
      function(error){
        alert("Plugin error: "+ error);
      },
      {
        preferGoogleMaps: true,
        urlScheme: "myscheme",
        backButtonText: "Back"
    });

This will result in a URL like: 

comgooglemaps-x-callback://?daddr="London, UK"&saddr="Manchester, UK"
   &x-success=myscheme://?resume=true
   &x-source=Back


 I will add official documented support with examples when I get time.

**Comment by saurabhkrishnan09** [comment]
Hi,

We have given the code as shown below. 

 launchnavigator.navigate("aSourceAddress",
                "bDestinationAddress",
                function () {
                    alert("plugin success map");
                },
                function (error) {
                    alert("plugin error: " + error);
                },
                {
                    preferGoogleMaps: true,
                    urlScheme: "TestMap2",
                    backButtonText: "TestMap2"
                });


Its switching to google maps app and navigating perfectly. 
But after we reach to destination, it does not come back to our app automatically.

We have also used custom URL plugin as available from- https://github.com/Telerik-Verified-Plugins/Custom-URL-scheme

**Comment by dpa99c** [comment]
@saurabhkrishnan09 The reason your app is not brought back on reaching the destination automatically is because this is not the behaviour Google Maps implements in response to an x-callback request. So far as I'm aware, it's not possible to get Google Maps on iOS to automatically switch back to your app once the destination is reached.

As noted in [this issue](https://github.com/dpa99c/phonegap-launch-navigator/issues/18), the current behaviour of Google Maps when invoked via the x-callback URL scheme is to display a "back" button for about 15 seconds before it disappears. Although this is not ideal, the launch navigator plugin has no control over this - it is up to Google Maps how to handle the x-callback request and this is how they've decided to use it.

**Comment by bau720123** [comment]
+1

**Comment by dpa99c** [comment]
Closing as the requested behaviour requires changes to Google Maps app, not this plugin.

**Comment by AnithaM** [comment]
Is there any possibility to add button on navigation map or any success callback after reach destination?. Thanks for the help in advance

**Comment by dpa99c** [comment]
@AnithaM No, that's not possible. It would require the launched navigator application (e.g. Google Maps, Waze, Navigon) to support some sort of common feedback scheme - which they do not.

Some individual applications have the capacity to feedback information to another application, e.g. Waze via the Waze SDK, however this requires integration of their specific SDK into your app and them to explicitly whitelist your app package ID, which is far beyond the scope of this plugin.

**Comment by AnithaM** [comment]
ok thank you. I will check in waze.

**Comment by BboyEcuachi** [comment]
+1
