### ISSUE TITLE
isAppAvailable fails on W10

### ISSUE THREAD

**Issue by Reubend** [dpa99c/phonegap-launch-navigator#86]
The isAppAvailable function does not seem to work properly with Google Maps on Windows 10 universal apps. Here's an example of some code where you can see the issue:
```
launchnavigator.isAppAvailable(launchnavigator.APP.GOOGLE_MAPS, function (isAvailable) {
        if (isAvailable) {
            //This will always run, even if GMaps isn't really installed
        } else {
            //This will never run, even when GMaps isn't really installed
        }
    });
```

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/phonegap-launch-navigator#supported-navigation-apps), the stock (Bing) Maps is currently the only supported app on the Windows platform. This is because (at least as far as I'm aware) it's not possible to detect the availability or programmatically launch other apps on Windows.

However, this is still a bug, because `isAvailable` should be `false` for any app other than `launchnavigator.APP.BING_MAPS`, but the plugin is currently [hard-coded to always return true](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/windows/launchnavigator.js#L39).
