### ISSUE TITLE
I dont use typescript and launchnavigator is not defined

### ISSUE THREAD

**Issue by rodrigokestler** [dpa99c/phonegap-launch-navigator#89]
I dont use typescript and launchnavigator is not defined. How do I define launchnavigator so that I can use the plugin? I cant install the plugin from npm, I have to do it manually.

**Comment by dpa99c** [comment]
Why can't you install the plugin from npm and have to do it manually?

**Comment by rodrigokestler** [comment]
I get the following error: Error: Uh oh!
ENOENT: no such file or directory, open '/Users/pizotesoft/Documents/Celumanix 2/I Love Concerts Android copy/app/platforms/android/local.properties’

I am not interested in using it in android, so when I try to adding it only to iOS i get the following error:
Error: Cannot find plugin.xml for plugin 'package'. Please try adding it again.

**Comment by dpa99c** [comment]
Looks like you are using spaces in the folder names which is a bad idea; that's likely to cause path issues when node modules are trying to resolve paths.

Try cloning the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) to `/Users/pizotesoft/Documents/phonegap-launch-navigator-example`, then building and running the SimpleExample app to validate your build environment (and the plugin).

**Comment by rodrigokestler** [comment]
I cant build the example project because of the following error: Command failed with exit code 65 and Im a little bit short on time to update all the environment, adding the platforms, all the plugins, etc. Do you have any instructions on adding the plugin manually? I have not used Typescript before and I see it is in that file that you define launchnavigator. (I have already added the .h and .m files, the feature in the config.xml, the strings in the info.plist and the javascript in my index.html)

**Comment by dpa99c** [comment]
The typescript definition will not be of any use to you. It's just there to stop ECMAScript 6 compilers from throwing errors, but ultimately it all gets compiled back to ECMAScript 5 anyway (at the moment).

The `window.launchnavigator` object is created because the Cordova plugin installation process translates the [merges line in the plugin.xml](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L30) into a RequireJS module. If you simply copy in [launchnavigator.js](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/www/ios/launchnavigator.js) this will not happen. Even if you manually defined the module declaration, Cordova still won't know about it as the

**Comment by dpa99c** [comment]
oops, didn't mean to do that...

**Comment by dpa99c** [comment]
As an alternate installation method, you can try using plugman to install direct from the github repo:

   $ npm install -g plugman

From the project root:

    $ plugman install --platform=ios --project=platforms/ios --plugin=https://github.com/dpa99c/phonegap-launch-navigator

If that doesn't work, then your environment really is screwed.

**Comment by rodrigokestler** [comment]
Thank you very much for all your help and quick responses. I really appreciate it. I'll post in a while what worked for me.

**Comment by dpa99c** [comment]
Reopen if still an issue
