### ISSUE TITLE
Support for including Stops or Waypoints?

### ISSUE THREAD

**Issue by bookrides** [dpa99c/phonegap-launch-navigator#98]
Would it be possible to add a way to include stops or waypoints? Currently there is only a way to specify origin and desination, but I believe both Google and Apple maps support stops. Thanks for the awesome plugin!

**Comment by rameshsr** [comment]
Though it is not documented, I tried this way to specify multiple way points when launching Google Maps and it worked.

launchnavigator.navigate('waypoint1+to:waypoint2+to:waypoint3', {start: 'some place'});

Here waypoint can be either name of the place or lat,lng

Please note that Google Maps allows giving multiple way points using the +to: syntax. So I tried this way. I don't know if the syntax is same if opening Apple Maps.

If there is a better way to achieve this, I would appreciate suggestions.

**Comment by dpa99c** [comment]
The plugin [launches Apple Maps](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/CMMapLauncher.m#L219) using the [MapKit API](https://developer.apple.com/reference/mapkit) rather than using a URL scheme as for the other supported apps. So adding additional waypoints in a URL-parameterised syntax will not work. The [openMaps method](https://developer.apple.com/reference/mapkit/mkmapitem/1452207-openmaps) used to launch Apple Maps supports an array of multiple [MKMapItem](https://developer.apple.com/reference/mapkit/mkmapitem) objects, so it may be the case if there are more than 2, that the intermediate ones are used as waypoints - I can't find any documentation to support this though, so an empirical test may be required to confirm this.

**Comment by bookrides** [comment]
Just thought I'd update this thread, it appears Apple Maps only supports mapping from point A to point B. Sad. [https://discussions.apple.com/thread/5606476?tstart=0](url)

**Comment by iget-master** [comment]
@rameshsr's solution seems to doesn't work anymore. Google maps says that cannot found the Coordinates, aparently is an issue with the `+` part of `+to:`

**Comment by jamesnogra** [comment]
Hi, is there a way to make multiple waypoints possible in Waze? I tried the solution above but it doesn't work. :)

**Comment by dpa99c** [comment]
@jamesnogra From the [documented URL scheme for Waze](https://developers.google.com/waze/deeplinks/#navigate-to-location), it seems multiple waypoints are not supported.

**Comment by jamesnogra** [comment]
@dpa99c thanks for the quick reply. that's a bummer though.
